### ISSUE TITLE
Visualization of the sorted topics

### ISSUE THREAD

**Issue by SteffenPegenau** [moodlepeers/moodle-mod_groupformation#16]
A teacher brought up this question: Is it possible to see how the students like the topics?

Maybe by giving every position in the sorted list a score, building sums for the topics and visualize them in a bar chart?

| Position 1 | 10 Points |
| --- | --- |
| Position 2 | 9 Points |
| ... | ... |
| Position 10 | 1 Point |

I am really not sure whether such a diagram was interpretable...

**Comment by rroepke** [comment]
We look into it for the summer term version comming early 2017.

**Comment by jkonert** [comment]
done with enhancement for #22 and #16
