### ISSUE TITLE
Unusable slow: grouping_view.php?id=XXX&do_show=grouping 

### ISSUE THREAD

**Issue by SteffenPegenau** [moodlepeers/moodle-mod_groupformation#17]
As mentioned in private Mails, opening the URL is so slow that it is impossible to build the groups.

**Comment by rroepke** [comment]
This issue is not recreatable because it might be depended on the moodle DB wrapper or the used DB but not the functionality of the requested view

**Comment by rroepke** [comment]
Needs to be tested again with new release (coming soon).

**Comment by rroepke** [comment]
Expected to be fixed but needs to be tested by @thomaswilker and/or @Nullmann. Feedback appreciated

**Comment by jkonert** [comment]
not reproducable any more.
