### ISSUE TITLE
Accessing URL hacks via links

### ISSUE THREAD

**Issue by SteffenPegenau** [moodlepeers/moodle-mod_groupformation#18]
There are many nice little hacks, accessible by url manipulations like file.php?do_the_hack=1. For example to control the grouping process or to create dummy-users for testing purposes.

As administrator/course creator/manager it would be nice to have links in the activity to access these hacks directly.

**Comment by rroepke** [comment]
We will take this into consideration for the next enhancement

**Comment by jkonert** [comment]
If Moodle is set to DEBUG mode, the buttons will appear in groupformation for admins.
