### ISSUE TITLE
Wrong ordering?

### ISSUE THREAD

**Issue by Nullmann** [moodlepeers/moodle-mod_groupformation#21]
There has been reports from students that the ordering for the topics are messed up and many got their last wanted topic. 

Maybe the algorithm sorts the topics wrong?

Tthere should be an indicator in which sequence the topics should be sorted. The students reportedly sorted from top to bottom which would have been my first thinking also.

**Comment by rroepke** [comment]
Indeed, there was a small bug in how to handle the groups. 

I prepared manual fixes but a regrouping needs to be done in order to fix the broken groups. I will message you those via email since the current version differs from your installed version.

**Comment by rroepke** [comment]
Closed with commit 6e5382a8da7e098eaa7d2afce201ffb61d1385a3
