### ISSUE TITLE
Typo in the plugin description 

### ISSUE THREAD

**Issue by mudrd8mz** [moodlepeers/moodle-mod_groupformation#23]
The plugin description at https://moodle.org/plugins/mod_groupformation reads:
```
... Depending on the szenario you have choosen, preknowledges ...
```
There should be just "scenario".

**Comment by jkonert** [comment]
Documentation updated at [Moodle.org](https://moodle.org/plugins/mod_groupformation) and here in [wiki](https://github.com/moodlepeers/moodle-mod_groupformation/wiki).

Fixed.
