### ISSUE TITLE
Inconsistent handling of HTML tags in topic and knowledge

### ISSUE THREAD

**Issue by mudrd8mz** [moodlepeers/moodle-mod_groupformation#24]
If I specify the topics with HTML tags (such as `<h1>Topic 1</h1>`, `<h1>Topic 2</h1>` etc) and use the same for the list of knowledge questions, the behaviour is inconsistent.

* Knowledge questions seem to be handled differently from topics.
* Things look differently in the preview and then later in actual usage.

Maybe you want to simply consider all these fields as plain text fields and always use the `s()` function when printing them via PHP, and the appropriate way to handle them via JS.

**Comment by jkonert** [comment]
Tag usage in topics/knowledge leads to empty fields in questionnaire. Better behaviour: Convert all tags to HTML safe representation.

**Comment by rroepke** [comment]
Maybe you can find the thing to change in [settings_functions.js](https://github.com/moodlepeers/moodle-mod_groupformation/blob/master/js/settings_functions.js)
