### ISSUE TITLE
Problem when both topics and knowledge questions are defined

### ISSUE THREAD

**Issue by mudrd8mz** [moodlepeers/moodle-mod_groupformation#27]
In the activity form, as a teacher I have enabled both "I want to include knowledge questions" and "I want to define topics" (the UI allows me to do that). But then for students, only topics drag & drop ordering is displayed and no other questions (neither my knowledge ones nor the inbuilt ones).

**Comment by rroepke** [comment]
For now, this is intentional. But we should work on a better concept for the topic option.
