### ISSUE TITLE
Requires non-standard libraries

### ISSUE THREAD

**Issue by mudrd8mz** [moodlepeers/moodle-mod_groupformation#3]
Attempting to install the plugin on clean Moodle 2.9 installation dies with error
```
Fatal error: require_once(): Failed opening required
'.../moodle/lib/groupal/classes/criteria/specific_criterion.php' 
```
caused by a code like this

    require_once($CFG->dirroot . '/lib/groupal/classes/criteria/topic_criterion.php');

There is no such groupal library in moodle.

**Comment by jkonert** [comment]
Thanks for your interest. Ideed this plugin requires the library to be installed as mentioned in the docs. Install https://github.com/moodlepeers/moodle-lib_groupal as well and it works.
