### ISSUE TITLE
7 invalid/missing string identifiers for english (EN)

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#33]
Invalid get_string() identifier: 'groupformation:editsettings' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:editsettings'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:onlymanager' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:onlymanager'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:onlyread' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:onlyread'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:onlystudent' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:onlystudent'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:readsettings' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:readsettings'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:submit' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:submit'] = ''; in mod/groupformation/lang/en/groupformation.php?

Invalid get_string() identifier: 'groupformation:view' or component 'mod_groupformation'. Perhaps you are missing $string['groupformation:view'] = ''; in mod/groupformation/lang/en/groupformation.php?

**Comment by rroepke** [comment]
Fixed with commit 52369ece6606d35053292cd8b8bcf2302579b6e4
