### ISSUE TITLE
show topic-offering ONLY when selecting "presentation groups" and DON'T offer topics for the other two scenarios

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#43]
In order to avoid irritation for teachers, only offer the topics for the thrid scenario.
Disable the setting completely (and hide it) for the other two scenarios.

This prevents that teachers are surprised that no other question is asked when they activate topics.

**Comment by jkonert** [comment]
more precisely: Deselect/hide knowledge area when topics are selected and vice versa.
Maybe not auto-deselect but bring a warning when the second (=both) is activated by the user.

(this lets the user see, that still two things are possible/available, but only one can be active at the same time)

**Comment by rroepke** [comment]
Closed with commit 0c14f60
