### ISSUE TITLE
PHP 5.5 Abhängigkeit wegen self::class entfernen!

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#5]
Für den Einsatz im Mathevorkurs muss PHP 5.4 Kompatibilität her.  Es wird aber im Code ein self::class verwendet, um auf die eigene Klasse zu verweisen. Das ist erst in V 5.5 gültig.
Bspw. `in /lib/classes/algorithms/basic_algorithm.php`  Zeile 174
`$this->cohort->whichMatcherUsed = self::class;`

Workaround: siehe http://stackoverflow.com/a/29862945  mit `get_class($this)`  ?  
Ausprobieren ob es das gleiche liefert.

**Comment by rroepke** [comment]
Gibt es auch Probleme mit den static::method_call() Aufrufen wie bspw.
classes/moodle_interface/job_manager.php Zeile 80
?

**Comment by jkonert** [comment]
unklar.  Vermutlich nicht, da explizit das Schlüsselwort "class" in Version 5.4 sowie Version 5.6 nicht gültig ist.  In Version 5.5 wohl nur.

**Comment by jkonert** [comment]
Current fixes in Development branch tested, commit 77559ae  
runs PHP 5.4.  FIXED
