### ISSUE TITLE
Change message for disabled "notify teacher" function 

### ISSUE THREAD

**Issue by thomaswilker** [moodlepeers/moodle-mod_groupformation#51]
lang/de/groupformation.php
1) change value of 

$string['emailnotifications']
$string['emailnotifications_info']
$string['emailnotifications_description']

"Die automatische Benachrichtigung über abgeschlossene Gruppenformationen ist momentan leider nicht verfügbar."

2) uncheck the related checkbox

![groupformation2](https://cloud.githubusercontent.com/assets/7371388/24745989/e003bc9a-1ab7-11e7-9661-a8d3b495187a.PNG)

**Comment by rroepke** [comment]
Fixed by dd6400930f7eb1cdf3467a21f386df0256e429e8

**Comment by thomaswilker** [comment]
The two sentences are contradictory:

"Die automatische Benachrichtigung über abgeschlossene Gruppenformationen ist momentan leider nicht verfügbar. Sie werden via Moodle benachrichtigt, wenn sie abgeschlossen ist."

Suggestion: Remove the second sentence

**Comment by rroepke** [comment]
Done
