### ISSUE TITLE
"my group" does not update list of users due to leaves and manual changes

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#61]
After group formation, users can see their group members via tab "my group". The list of members does not change if

- a user leaves the whole moodle course
- a user was manually removed or added (by teacher via Moodle)

While it is a good idea to show the orginally created group members, it would be helpful to show the current state, too. 
e.g.

1. mark removed users gray (or deactivated)
2. mark later added users with a * (and add a short mouseover text)

Thus users clearly see who is currently in the group and below who "was" but is not any more.
Technically simply compare current Moodle group members to the members of mod_groupformation table and if diff, move missing people to the bottom and move new members before them. Mark both to be recognizable by users.

**Comment by rroepke** [comment]
Now, changes are displayed. But it will not be distinguished between leaving group or course.

![image](https://user-images.githubusercontent.com/10012484/39887139-b9d47a22-5491-11e8-8788-9a728a307e39.png)
