### ISSUE TITLE
EU Datenschutzverordnung: Download aller über "mich" gespeicherten Daten (aus allen Kursen) anbieten

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#63]
Neben dem Download als XML Import/export  einen Button anbieten, der mit 
EINEM Klick
dem Nutzer ALLE aus ALLEn Kursen über ihn gespeichertden Daten liefert.
Format? unklar, Dateschutzverordnung ansehen. XML wäre am einfachsten.

Deadline Mai 2018!

**Comment by rroepke** [comment]
Is available on current master
