### ISSUE TITLE
The english language string in questionnaire_availability_info_until | groupformation is in German

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodlepeers/moodle-mod_groupformation#65]
Hi,
The English language string at questionnaire_availability_info_until | groupformation is in the German language. I could not reliably translate it into English. Please help:

Der Fragebogen ist noch bis {$a->end} Uhr freigeschaltet.

**Comment by rroepke** [comment]
Fixed with b3e8f11b0c1c59a4a86214addd36ffbafc838825
