### ISSUE TITLE
externallib

### ISSUE THREAD

**Issue by sventi77** [moodlepeers/moodle-mod_groupformation#66]
- [x] Funktionen um relevante Werte für user_progressbar. würde sagen anzahl der ausgefüllten Seiten und generelle Seitenanzahl des Fragebogen wäre schon ganz gut. Sonst bereits beantwortete Fragen und Fragen insgesamt
- [x] Ebenso für teacher_progressbar. Da könnte man dann Studenten die den Fragebogen submitted haben und Studenten die den überhaupt bearbeiten können

**Comment by jkonert** [comment]
as it is fixed, it can be closed.
