### ISSUE TITLE
(cron) partisipant_parser.php:85 Clone on NULL object causes exception

### ISSUE THREAD

**Issue by jkonert** [moodlepeers/moodle-mod_groupformation#70]
At university setup, cron produces an exception which causes all other crons in Moodle to not run through.
There needs to be investigates, where the NULL object comes from. If it is a usual case, an if-else is needed.
Additionally probably a try-catch which issues a warning to log on catch-case.

Here is a detailed cron-log, provided by HRZ.
--------------------------------
SELECT * FROM mdl_task_scheduled WHERE classname = $1
[array (
  0 => '\\mod_groupformation\\task\\build_groups_task',
)]
--------------------------------
Query took: 0.00045108795166016 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_user WHERE id = $1 AND deleted = $2
[array (
  0 => '1',
  1 => 0,
)]
--------------------------------
Query took: 0.0011410713195801 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_context WHERE contextlevel = $1 AND instanceid = $2
[array (
  0 => 50,
  1 => '1',
)]
--------------------------------
Query took: 0.00026202201843262 seconds.
--------------------------------
Execute scheduled task: Task zur Gruppenbildung (mod_groupformation\task\build_groups_task)
--------------------------------
SELECT * FROM mdl_lock_db WHERE resourcekey = $1
[array (
  0 => 'core_cron',
)]
--------------------------------
Query took: 0.00041103363037109 seconds.
--------------------------------
--------------------------------
SELECT pg_try_advisory_lock($1, $2) AS locked
[array (
  0 => 1289808297,
  1 => '1',
)]
--------------------------------
Query took: 0.00023293495178223 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_lock_db WHERE resourcekey = $1
[array (
  0 => '\\mod_groupformation\\task\\build_groups_task',
)]
--------------------------------
Query took: 0.00021004676818848 seconds.
--------------------------------
--------------------------------
SELECT pg_try_advisory_lock($1, $2) AS locked
[array (
  0 => 1289808297,
  1 => '16423',
)]
--------------------------------
Query took: 0.00017189979553223 seconds.
--------------------------------
--------------------------------
SELECT pg_advisory_unlock($1, $2) AS unlocked
[array (
  0 => 1289808297,
  1 => '1',
)]
--------------------------------
Query took: 0.00018906593322754 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_jobs WHERE waiting = $1 AND started = $2 AND aborted = $3 AND done = $4 AND groups_generated = $5 AND groups_adopted = $6 
[array (
  0 => 0,
  1 => 0,
  2 => 1,
  3 => 0,
  4 => 0,
  5 => 0,
)]
--------------------------------
Query took: 0.00036406517028809 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_jobs WHERE waiting = $1 AND started = $2 AND aborted = $3 AND done = $4 AND groups_generated = $5 AND groups_adopted = $6 
[array (
  0 => 1,
  1 => 0,
  2 => 0,
  3 => 0,
  4 => 0,
  5 => 0,
)]
--------------------------------
Query took: 0.0002281665802002 seconds.
--------------------------------
--------------------------------
SELECT course FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00030708312988281 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_context WHERE contextlevel = $1 AND instanceid = $2
[array (
  0 => 50,
  1 => '2356',
)]
--------------------------------
Query took: 0.00024604797363281 seconds.
--------------------------------
--------------------------------
SELECT rc.id, rc.roleid, rc.permission, ctx.path
              FROM mdl_role_capabilities rc
              JOIN mdl_context ctx on rc.contextid = ctx.id
             WHERE rc.contextid IN ($1,$2,$3,$4) AND rc.capability = $5
[array (
  0 => '1',
  1 => '10',
  2 => '218',
  3 => '116414',
  4 => 'mod/groupformation:onlystudent',
)]
--------------------------------
Query took: 0.00069594383239746 seconds.
--------------------------------
--------------------------------
SELECT u.*
              FROM mdl_user u
              JOIN (SELECT DISTINCT eu1_u.id
              FROM mdl_user eu1_u
            JOIN mdl_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN mdl_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = $1)
JOIN mdl_role_assignments eu1_ra3
                    ON (eu1_ra3.userid = eu1_u.id
                    AND eu1_ra3.roleid IN (5)
                    AND eu1_ra3.contextid IN (1,10,218,116414))
             WHERE 1 = 1 AND (eu1_u.id <> $2) AND eu1_u.deleted = 0) je ON je.id = u.id
             WHERE u.deleted = 0 ORDER BY u.lastname, u.firstname, u.id
[array (
  0 => '2356',
  1 => '24635',
)]
--------------------------------
Query took: 0.0042891502380371 seconds.
--------------------------------
--------------------------------
SELECT rc.id, rc.roleid, rc.permission, ctx.path
              FROM mdl_role_capabilities rc
              JOIN mdl_context ctx on rc.contextid = ctx.id
             WHERE rc.contextid IN ($1,$2,$3,$4) AND rc.capability = $5
[array (
  0 => '1',
  1 => '10',
  2 => '218',
  3 => '116414',
  4 => 'mod/groupformation:editsettings',
)]
--------------------------------
Query took: 0.00037693977355957 seconds.
--------------------------------
--------------------------------
SELECT u.*
              FROM mdl_user u
              JOIN (SELECT DISTINCT eu2_u.id
              FROM mdl_user eu2_u
            JOIN mdl_user_enrolments ej2_ue ON ej2_ue.userid = eu2_u.id
JOIN mdl_enrol ej2_e ON (ej2_e.id = ej2_ue.enrolid AND ej2_e.courseid = $1)
JOIN mdl_role_assignments eu2_ra3
                    ON (eu2_ra3.userid = eu2_u.id
                    AND eu2_ra3.roleid IN (3,10,11,1)
                    AND eu2_ra3.contextid IN (1,10,218,116414))
             WHERE 1 = 1 AND (eu2_u.id <> $2) AND eu2_u.deleted = 0) je ON je.id = u.id
             WHERE u.deleted = 0 ORDER BY u.lastname, u.firstname, u.id
[array (
  0 => '2356',
  1 => '24635',
)]
--------------------------------
Query took: 0.0017189979553223 seconds.
--------------------------------
--------------------------------
SELECT onlyactivestudents FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00023794174194336 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.0002751350402832 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario  
[array (
)]
--------------------------------
Query took: 0.00027108192443848 seconds.
--------------------------------
--------------------------------
SELECT id FROM mdl_groupformation_scenario WHERE assigned_id = $1
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.00020909309387207 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario_cats WHERE scenario = $1 
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.00026702880859375 seconds.
--------------------------------
--------------------------------
SELECT category FROM mdl_groupformation_q_version WHERE id = $1
[array (
  0 => '8',
)]
--------------------------------
Query took: 0.00029587745666504 seconds.
--------------------------------
--------------------------------
SELECT knowledgenumber FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00032210350036621 seconds.
--------------------------------
--------------------------------
SELECT knowledge FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.0002751350402832 seconds.
--------------------------------
--------------------------------
SELECT topicnumber FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00029087066650391 seconds.
--------------------------------
--------------------------------
SELECT topicnumber FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00026988983154297 seconds.
--------------------------------
--------------------------------
SELECT topics FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00023293495178223 seconds.
--------------------------------
--------------------------------
SELECT userid FROM mdl_groupformation_answers WHERE groupformation = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.0003969669342041 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 50585,
)]
--------------------------------
Query took: 0.00040507316589355 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 56607,
)]
--------------------------------
Query took: 0.00020480155944824 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 52979,
)]
--------------------------------
Query took: 0.00019693374633789 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 47407,
)]
--------------------------------
Query took: 0.00016093254089355 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 54853,
)]
--------------------------------
Query took: 0.00019383430480957 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 65265,
)]
--------------------------------
Query took: 0.00020003318786621 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 43196,
)]
--------------------------------
Query took: 0.00019502639770508 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 41469,
)]
--------------------------------
Query took: 0.00019288063049316 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 54774,
)]
--------------------------------
Query took: 0.00019192695617676 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 52183,
)]
--------------------------------
Query took: 0.00019192695617676 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 47003,
)]
--------------------------------
Query took: 0.00021600723266602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 54957,
)]
--------------------------------
Query took: 0.00019097328186035 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 50766,
)]
--------------------------------
Query took: 0.00015592575073242 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 52857,
)]
--------------------------------
Query took: 0.00015497207641602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 50733,
)]
--------------------------------
Query took: 0.0001680850982666 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 55486,
)]
--------------------------------
Query took: 0.00015497207641602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 48441,
)]
--------------------------------
Query took: 0.00014090538024902 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 52201,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 36916,
)]
--------------------------------
Query took: 0.00015497207641602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 46633,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 51532,
)]
--------------------------------
Query took: 0.00013995170593262 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 41041,
)]
--------------------------------
Query took: 0.00015783309936523 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 55640,
)]
--------------------------------
Query took: 0.00015497207641602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 45666,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 36883,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 36568,
)]
--------------------------------
Query took: 0.00015497207641602 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 51761,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 51869,
)]
--------------------------------
Query took: 0.00015521049499512 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 47573,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 55508,
)]
--------------------------------
Query took: 0.00013995170593262 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 46448,
)]
--------------------------------
Query took: 0.00014209747314453 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 51806,
)]
--------------------------------
Query took: 0.00014019012451172 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 50945,
)]
--------------------------------
Query took: 0.00013995170593262 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 46971,
)]
--------------------------------
Query took: 0.00014090538024902 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 51652,
)]
--------------------------------
Query took: 0.00013995170593262 seconds.
--------------------------------
--------------------------------
SELECT filtered FROM mdl_groupformation_users WHERE groupformation = $1 AND userid = $2
[array (
  0 => '6',
  1 => 52751,
)]
--------------------------------
Query took: 0.00015401840209961 seconds.
--------------------------------
--------------------------------
SELECT topics FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00014686584472656 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00019216537475586 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario  
[array (
)]
--------------------------------
Query took: 0.00011992454528809 seconds.
--------------------------------
--------------------------------
SELECT id FROM mdl_groupformation_scenario WHERE assigned_id = $1
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.00014686584472656 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00018906593322754 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario  
[array (
)]
--------------------------------
Query took: 0.00013113021850586 seconds.
--------------------------------
--------------------------------
SELECT id FROM mdl_groupformation_scenario WHERE assigned_id = $1
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.0001380443572998 seconds.
--------------------------------
--------------------------------
SELECT topics FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00014495849609375 seconds.
--------------------------------
--------------------------------
SELECT groupoption FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00015091896057129 seconds.
--------------------------------
--------------------------------
SELECT maxmembers FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00014996528625488 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00018596649169922 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario  
[array (
)]
--------------------------------
Query took: 0.00011682510375977 seconds.
--------------------------------
--------------------------------
SELECT id FROM mdl_groupformation_scenario WHERE assigned_id = $1
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.00012302398681641 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00018191337585449 seconds.
--------------------------------
--------------------------------
SELECT * FROM mdl_groupformation_scenario  
[array (
)]
--------------------------------
Query took: 0.00013613700866699 seconds.
--------------------------------
--------------------------------
SELECT id FROM mdl_groupformation_scenario WHERE assigned_id = $1
[array (
  0 => '3',
)]
--------------------------------
Query took: 0.00014400482177734 seconds.
--------------------------------
--------------------------------
SELECT topicnumber FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.0001518726348877 seconds.
--------------------------------
--------------------------------
SELECT knowledgenumber FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.0001671314239502 seconds.
--------------------------------
--------------------------------
SELECT evaluationmethod FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00017499923706055 seconds.
--------------------------------
--------------------------------
SELECT evaluationmethod FROM mdl_groupformation WHERE id = $1
[array (
  0 => '6',
)]
--------------------------------
Query took: 0.00016498565673828 seconds.
--------------------------------
/var/www/moodle/mod/groupformation/classes/grouping/participant_parser.php:83:
class stdClass#225 (1) {
  public $id =>
  int(41469)
}
/var/www/moodle/mod/groupformation/classes/grouping/participant_parser.php:84:
string(4) "<br>"
/var/www/moodle/mod/groupformation/classes/grouping/participant_parser.php:85:
NULL
!!! Fehler: __clone method called on non-object !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 87 of /mod/groupformation/lib/classes/algorithms/basic_algorithm.php: Error thrown
* line 174 of /mod/groupformation/classes/grouping/grouping.php: call to mod_groupformation_basic_algorithm-&gt;__construct()
* line 140 of /mod/groupformation/classes/grouping/grouping.php: call to mod_groupformation_grouping-&gt;build_groupal_cohort()
* line 103 of /mod/groupformation/classes/grouping/basic_grouping.php: call to mod_groupformation_grouping-&gt;build_cohort()
* line 343 of /mod/groupformation/classes/moodle_interface/advanced_job_manager.php: call to mod_groupformation_basic_grouping-&gt;run_grouping()
* line 84 of /mod/groupformation/classes/task/build_groups_task.php: call to mod_groupformation_advanced_job_manager::do_groupal()
* line 65 of /mod/groupformation/classes/task/build_groups_task.php: call to mod_groupformation\task\build_groups_task-&gt;do_job()
* line 156 of /admin/tool/task/cli/schedule_task.php: call to mod_groupformation\task\build_groups_task-&gt;execute()
 !!

**Comment by rroepke** [comment]
Cannot be rebuild but code was checked and should be running
