### ISSUE TITLE
Support for Moodle 3.11 (and 4.x)?

### ISSUE THREAD

**Issue by Marx1st** [moodlepeers/moodle-mod_groupformation#90]
Hi!

Any plans on supporting Moodle 3.11 (and 4.x)?

**Comment by rroepke** [comment]
Sure! I will let you know when the new release is ready. It just moved up on our agenda 😁

**Comment by FelixDiLenarda** [comment]
@rroepke Any news on 4.0 and 4.1?

Thank you!

**Comment by rroepke** [comment]
Happy New Years! Just preparing the new version :-) I will upload it by the end of the week.
